version: '2'
services:
    wordpress:
        image: dsifford/wordpress:nginx
        links:
            - db
        ports:
            - 22222:22222
            - 8080:80
            - 443:443
        volumes:
          - ./data:/data # The directory where your SQL backup is stored (if applicable)
          - ./myplugin:/var/www/yoursite.com/htdocs/wp-content/plugins/myplugin # Plugin volume
          - ./mytheme:/var/www/yoursite.com/htdocs/wp-content/themes/mytheme # Theme volume
        environment:
            # Build
            PHP_VERSION: 5.6
            LOCALHOST: 'false'
            SITE_NAME: yoursite.com

            # Database
            DB_PASS: root # must match below
            DB_NAME: wordpress
            DB_USER: root

            # WordPress
            ADMIN_EMAIL: admin@wordpress.com
            PLUGINS: >-
              academic-bloggers-toolkit,
              co-authors-plus,
              rest-api
            THEMES: twentysixteen
            SEARCH_REPLACE: yoursite.com,localhost:8080
            WP_DEBUG: 'false'
            WP_DEBUG_LOG: 'false'
            WP_DEBUG_DISPLAY: 'true'
    db: # Must be named 'db'
        image: mariadb:10
        ports:
            - 3306:3306
        volumes_from:
            - data
        environment:
            MYSQL_ROOT_PASSWORD: root
    data:
        image: busybox
        volumes:
            - /var/lib/mysql
