version: '2'
services:
    wordpress:
        image: dsifford/wordpress:nginx
        links:
            - db
        ports:
            - 3000:9000
            - 22222:22222
            - 8080:80
            - 443:443
        environment:
            DB_PASS: root # must match below
            DB_NAME: wordpress
            SITE_NAME: aliemu.com
            LOCALHOST: 'true'
            PLUGINS: >-
              academic-bloggers-toolkit,
              co-authors-plus,
              rest-api
            SEARCH_REPLACE: yoursite.com,localhost:8080
            WP_DEBUG: 'true'
            WP_DEBUG_LOG: 'true'
            WP_DEBUG_DISPLAY: 'false'
    db: # Must be named 'db'
        image: mariadb:10
        ports:
            - 3306:3306
        volumes_from:
            - data
        environment:
            MYSQL_ROOT_PASSWORD: root
    data:
        image: busybox
        volumes:
            - /var/lib/mysql
