#!/bin/bash

[ "$DB_NAME" ] || DB_NAME='wordpress'
[ "$DB_PASS" ] || DB_PASS='root'

printf "=> Waiting for MySQL to initialize... "
while ! mysqladmin ping --host=db --password=$DB_PASS --silent; do
    sleep 1
done

printf "=> Generating wp.config.php file... "
/usr/local/bin/wp core config \
    --dbname="$DB_NAME" \
    --dbuser=root \
    --dbpass="$DB_PASS" \
    --dbhost='db:3306' \
    --allow-root

# .htaccess
printf "=> Generating .htaccess file... "
cat > /app/.htaccess <<EOF
# BEGIN WordPress
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.php [L]
</IfModule>
# END WordPress
EOF
printf "Done!\n"

printf "=> Wordpress setup complete!\n"
