#!/bin/bash

[ "$DB_NAME" ] || DB_NAME='wordpress'
[ "$DB_PASS" ] || DB_PASS='root'
[ "$SEARCH_REPLACE" ] || SEARCH_REPLACE=false

printf  "
=> Initializing database...
=====================================
  Database Host Address:  db
  Database Port Number:   3306
  Database Name:          %s
  Database Username:      root
=====================================
" "$DB_NAME"

printf "=> Creating database '%s'... " "$DB_NAME"
wp db create --allow-root

# If an SQL file exists in /data => load it
if [ "$(stat -t /data/*.sql >/dev/null 2>&1 && echo $?)" ]; then

    DATA_PATH=$(find /data/*.sql | head -n 1)
    printf "=> Loading data backup from %s... " "$DATA_PATH"
    wp db import "$DATA_PATH" --allow-root

    # If SEARCH_REPLACE is set => Replace URLs
    if [ "$SEARCH_REPLACE" != false ]; then

        printf "=> Replacing URLs... \n"
        BEFORE_URL=$(echo "$SEARCH_REPLACE" | cut -d ',' -f 1)
        AFTER_URL=$(echo "$SEARCH_REPLACE" | cut -d ',' -f 2)
        wp search-replace  "$BEFORE_URL" "$AFTER_URL" --skip-columns=guid --allow-root

    fi

else
    printf "%s\n" \
        "=> No database backup found. Initializing new database..." " " \
        "      DEFAULT DATABASE CREDENTIALS" \
        "=========================================" \
        " Site URL:       localhost:8080 " \
        " Site Title:     $DB_NAME" \
        " Admin Username: root" \
        " Admin Password: $DB_PASS" \
        " Admin Email:    admin@${DB_NAME}.com" \
        "=========================================" " "

    wp core install --allow-root \
        --url=localhost:8080 \
        --title="$DB_NAME" \
        --admin_user=root \
        --admin_password="$DB_PASS" \
        --admin_email=admin@"${DB_NAME}".com \
        --skip-email
fi

printf "=> Database initialization completed sucessfully!\n\n"
