#!/bin/bash

[ ! "$DB_NAME" ] && DB_NAME='wordpress'
[ ! "$DB_PASS" ] && DB_PASS='root'

printf "=> Creating wp-config.php... "
/usr/local/bin/wp core config \
    --dbname="$DB_NAME" \
    --dbuser=root \
    --dbpass="$DB_PASS" \
    --dbhost=db:3306 \
    --allow-root

i=0
while [ ! -f /app/wp-config.php ]; do
    [ $i -eq 15 ] && break
    sleep 1
    ((i++))
done
[ $i -lt 15 ] && printf "Done!\n" || printf "Failed.\n"

# .htaccess
printf "=> Creating .htaccess file... "
cat > /app/.htaccess <<EOF
# BEGIN WordPress
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.php [L]
</IfModule>
# END WordPress
EOF
printf "Done!\n"

printf "=> Wordpress setup complete!\n"
