#!/bin/bash

printf  "
=> Initializing Database...
=====================================
  Database Host Address:  db
  Database Port Number:   3306
  Database Name:          $DB_NAME
  Database Username:      root
=====================================
"

for i in {1..10}; do
    printf "=> Establishing database connection (attempt $i/10)..."
    DB_CONNECTABLE=$(mysql --user=root --password="$DB_PASS" --host=db --port=3306 -e 'status' >/dev/null 2>&1; echo "$?")
    if [[ DB_CONNECTABLE -eq 0 ]]; then
        printf "\n=> Database Connection Established!"
        break
    fi
    sleep 5
    printf "Failed."
done

if [[ $DB_CONNECTABLE -eq 0 ]]; then
    DB_EXISTS=$(mysql --user=root --password="$DB_PASS" --host=db --port=3306 -e "SHOW DATABASES LIKE '$DB_NAME';" 2>&1 |grep "$DB_NAME" > /dev/null ; echo "$?")

    if [[ DB_EXISTS -eq 1 ]]; then
        printf "=> Creating database $DB_NAME\n"
        RET=$(mysql --user=root --password="$DB_PASS" --host=db --port=3306 -e "CREATE DATABASE $DB_NAME")
        if [[ RET -ne 0 ]]; then
            printf "Cannot create database for wordpress\n"
            exit RET
        fi
    else
        printf "=> Skipped creation of database $DB_NAME – database already exists.\n"
    fi

    if [ $(mysql -N -s --user=root --password="$DB_PASS" --host=db --port=3306 -e \
        "select count(*) from information_schema.tables where \
            table_schema='$DB_NAME' and table_name='wp_posts';") -eq 0 ]; then
        if [ -f /data/database.sql ]; then
            printf "=> Loading initial database data to $DB_NAME\n"
            RET=$(mysql --user=root --password="$DB_PASS" --host=db --port=3306 "$DB_NAME" < /data/database.sql)
            if [[ RET -ne 0 ]]; then
                printf "Cannot load initial database data for wordpress\n"
                exit RET
            fi
        fi
    fi
else
    printf "Cannot connect to Mysql\n"
    exit "$DB_CONNECTABLE"
fi

printf "=> Database Initialization Completed!"

touch /.mysql_db_created
